services:
  postgres:
    image: postgres:16-alpine
    container_name: interviewos-postgres
    environment:
      POSTGRES_DB: interviewos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - interviewos-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d interviewos']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - interviewos
  redis:
    image: redis:7-alpine
    container_name: interviewos-redis
    ports:
      - '6379:6379'
    volumes:
      - interviewos-redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - interviewos

volumes:
  interviewos-postgres:
  interviewos-redis:

networks:
  interviewos:
    name: interviewos
