import {
  LearningPathItemStatus,
  ReviewItemType,
  ReviewRating,
  WeakConceptStatus,
} from '@interviewos/types'

import type { ReviewPageFixture } from './ReviewPage.types'

export const reviewPageFixture: ReviewPageFixture = {
  title: 'Review queue',
  subtitle: 'Spaced repetition keeps weak concepts from coming back to bite you.',
  dueLabel: '3 due today',
  queue: [
    {
      id: 'review-card-1',
      reviewItemId: 'review-item-1',
      title: 'Closures and lexical scope',
      type: ReviewItemType.TECHNICAL_NOTE,
      masteryPercent: 42,
      weaknessScore: 72,
      nextReviewLabel: 'Today',
      lastRating: ReviewRating.HARD,
      availableRatings: [
        ReviewRating.AGAIN,
        ReviewRating.HARD,
        ReviewRating.GOOD,
        ReviewRating.EASY,
      ],
    },
    {
      id: 'review-card-2',
      reviewItemId: 'review-item-2',
      title: 'Explain event loop microtasks',
      type: ReviewItemType.GENERATED_QUESTION,
      masteryPercent: 55,
      weaknessScore: 65,
      nextReviewLabel: 'Today',
      lastRating: ReviewRating.GOOD,
      availableRatings: [
        ReviewRating.AGAIN,
        ReviewRating.HARD,
        ReviewRating.GOOD,
        ReviewRating.EASY,
      ],
    },
    {
      id: 'review-card-3',
      reviewItemId: 'review-item-3',
      title: 'Subject-verb agreement',
      type: ReviewItemType.ENGLISH_NOTE,
      masteryPercent: 60,
      weaknessScore: 58,
      nextReviewLabel: 'Tomorrow',
      lastRating: ReviewRating.GOOD,
      availableRatings: [
        ReviewRating.AGAIN,
        ReviewRating.HARD,
        ReviewRating.GOOD,
        ReviewRating.EASY,
      ],
    },
    {
      id: 'review-card-4',
      reviewItemId: 'review-item-4',
      title: 'B-tree vs GIN indexes',
      type: ReviewItemType.TECHNICAL_NOTE,
      masteryPercent: 70,
      weaknessScore: 50,
      nextReviewLabel: 'In 2 days',
      lastRating: ReviewRating.EASY,
      availableRatings: [
        ReviewRating.AGAIN,
        ReviewRating.HARD,
        ReviewRating.GOOD,
        ReviewRating.EASY,
      ],
    },
    {
      id: 'review-card-5',
      reviewItemId: 'review-item-5',
      title: 'Token bucket vs sliding window',
      type: ReviewItemType.GENERATED_QUESTION,
      masteryPercent: 35,
      weaknessScore: 80,
      nextReviewLabel: 'Today',
      lastRating: ReviewRating.AGAIN,
      availableRatings: [
        ReviewRating.AGAIN,
        ReviewRating.HARD,
        ReviewRating.GOOD,
        ReviewRating.EASY,
      ],
    },
  ],
  learningPath: [
    {
      id: 'learning-path-1',
      title: 'Deep dive into JavaScript closures',
      detail: 'You missed this 3 times in the last 2 sessions.',
      typeLabel: 'Note',
      priorityScore: 92,
      status: LearningPathItemStatus.PENDING,
    },
    {
      id: 'learning-path-2',
      title: '5 system design tradeoff questions',
      detail: 'Weak concept identified in last review.',
      typeLabel: 'Practice',
      priorityScore: 84,
      status: LearningPathItemStatus.PENDING,
    },
    {
      id: 'learning-path-3',
      title: 'Practice conditional sentences',
      detail: 'Recurring English weakness in mock interviews.',
      typeLabel: 'English',
      priorityScore: 71,
      status: LearningPathItemStatus.IN_PROGRESS,
    },
  ],
  weakConcepts: [
    {
      id: 'weak-concept-1',
      concept: 'Closures',
      occurrenceCount: 6,
      masteryPercent: 38,
      status: WeakConceptStatus.ACTIVE,
    },
    {
      id: 'weak-concept-2',
      concept: 'Async flow / Promises',
      occurrenceCount: 5,
      masteryPercent: 52,
      status: WeakConceptStatus.ACTIVE,
    },
    {
      id: 'weak-concept-3',
      concept: 'SQL indexes',
      occurrenceCount: 4,
      masteryPercent: 60,
      status: WeakConceptStatus.ACTIVE,
    },
    {
      id: 'weak-concept-4',
      concept: 'System design tradeoffs',
      occurrenceCount: 3,
      masteryPercent: 45,
      status: WeakConceptStatus.ACTIVE,
    },
    {
      id: 'weak-concept-5',
      concept: 'React keys',
      occurrenceCount: 2,
      masteryPercent: 88,
      status: WeakConceptStatus.RESOLVED,
    },
    {
      id: 'weak-concept-6',
      concept: 'Verbose answers',
      occurrenceCount: 2,
      masteryPercent: 0,
      status: WeakConceptStatus.IGNORED,
    },
  ],
}
