import { NoteStatus, NoteType, QuestionDifficulty } from '@interviewos/types'

import type { NotebookFixture } from './NotebookPage.types'

const userId = 'user-001'

export const notebookFixture: NotebookFixture = {
  notes: [
    {
      id: 'note-react-fiber',
      userId,
      title: 'React reconciliation & the fiber architecture',
      topic: 'React',
      rawInput:
        'How React decides what to re-render, why keys matter, how interruption works, and what changed with concurrent rendering.',
      type: NoteType.CONCEPT,
      status: NoteStatus.INTERVIEW_READY,
      overrideRole: 'Senior Frontend Engineer',
      overrideLevel: null,
      overrideStack: ['React', 'TypeScript'],
      overrideGoals: ['Frontend architecture depth'],
      overrideEnglishLevel: null,
      preferredOutputStyle: 'Concise and interview-ready',
      structuredContent: {
        purpose: 'How React decides what to re-render, why keys matter, and how fiber enables interruption.',
        quickReference: [],
        coreConcepts: [],
        mentalModel: '',
        productionUsage: [],
        practicalExamples: [],
        commonPitfalls: [],
        debuggingChecklist: [],
        productionChecklist: [],
        seniorInterviewSignals: [],
      },
      createdAt: new Date('2026-06-01T08:00:00.000Z'),
      updatedAt: new Date('2026-06-05T05:20:00.000Z'),
      questionCount: 8,
      difficulty: QuestionDifficulty.HARD,
    },
    {
      id: 'note-node-loop',
      userId,
      title: 'Node.js event loop phases',
      topic: 'Node.js',
      rawInput:
        'Timers, pending callbacks, poll, check, close callbacks, and where microtasks fit in.',
      type: NoteType.LANGUAGE_SPECIFIC,
      status: NoteStatus.INTERVIEW_READY,
      overrideRole: null,
      overrideLevel: null,
      overrideStack: ['Node.js'],
      overrideGoals: [],
      overrideEnglishLevel: null,
      preferredOutputStyle: null,
      structuredContent: {
        purpose: 'Timers, pending callbacks, poll, check, close, and where microtasks fit in.',
        quickReference: [],
        coreConcepts: [],
        mentalModel: '',
        productionUsage: [],
        practicalExamples: [],
        commonPitfalls: [],
        debuggingChecklist: [],
        productionChecklist: [],
        seniorInterviewSignals: [],
      },
      createdAt: new Date('2026-05-30T11:00:00.000Z'),
      updatedAt: new Date('2026-06-04T02:00:00.000Z'),
      questionCount: 6,
      difficulty: QuestionDifficulty.MEDIUM,
    },
    {
      id: 'note-nest-di',
      userId,
      title: 'NestJS dependency injection in practice',
      topic: 'NestJS',
      rawInput:
        'Providers, scopes, custom tokens, module boundaries, and when forwardRef is justified.',
      type: NoteType.CONCEPT,
      status: NoteStatus.DRAFT,
      overrideRole: 'Backend Engineer',
      overrideLevel: null,
      overrideStack: ['NestJS', 'PostgreSQL'],
      overrideGoals: ['System thinking'],
      overrideEnglishLevel: null,
      preferredOutputStyle: null,
      structuredContent: null,
      createdAt: new Date('2026-06-02T09:00:00.000Z'),
      updatedAt: new Date('2026-06-02T09:00:00.000Z'),
      questionCount: 0,
      difficulty: QuestionDifficulty.MEDIUM,
    },
    {
      id: 'note-postgres-indexes',
      userId,
      title: 'PostgreSQL index types and when to use them',
      topic: 'PostgreSQL',
      rawInput:
        'B-tree, GIN, GiST, BRIN, partial indexes, covering indexes, and how to validate impact with execution plans.',
      type: NoteType.CONCEPT,
      status: NoteStatus.MASTERED,
      overrideRole: null,
      overrideLevel: null,
      overrideStack: ['PostgreSQL'],
      overrideGoals: ['Database performance'],
      overrideEnglishLevel: null,
      preferredOutputStyle: null,
      structuredContent: {
        purpose: 'B-tree, GIN, GiST, BRIN, partial and covering indexes.',
        quickReference: [],
        coreConcepts: [],
        mentalModel: '',
        productionUsage: [],
        practicalExamples: [],
        commonPitfalls: [],
        debuggingChecklist: [],
        productionChecklist: [],
        seniorInterviewSignals: [],
      },
      createdAt: new Date('2026-05-20T06:00:00.000Z'),
      updatedAt: new Date('2026-05-31T02:30:00.000Z'),
      questionCount: 5,
      difficulty: QuestionDifficulty.MEDIUM,
    },
    {
      id: 'note-rate-limiter',
      userId,
      title: 'Designing a distributed rate limiter',
      topic: 'System Design',
      rawInput:
        'Token bucket vs sliding window, Redis as shared store, consistency tradeoffs, and failure modes.',
      type: NoteType.SYSTEM_DESIGN,
      status: NoteStatus.REVIEWING,
      overrideRole: 'Senior Backend Engineer',
      overrideLevel: null,
      overrideStack: ['Redis', 'Node.js'],
      overrideGoals: ['Architecture depth'],
      overrideEnglishLevel: null,
      preferredOutputStyle: 'Tradeoff-oriented',
      structuredContent: {
        purpose: 'Token bucket vs sliding window, Redis as a shared store, and failure modes.',
        quickReference: [],
        coreConcepts: [],
        mentalModel: '',
        productionUsage: [],
        practicalExamples: [],
        commonPitfalls: [],
        debuggingChecklist: [],
        productionChecklist: [],
        seniorInterviewSignals: [],
      },
      createdAt: new Date('2026-05-15T08:00:00.000Z'),
      updatedAt: new Date('2026-05-28T01:00:00.000Z'),
      questionCount: 4,
      difficulty: QuestionDifficulty.HARD,
    },
    {
      id: 'note-star-stories',
      userId,
      title: 'STAR-format answers for behavioral rounds',
      topic: 'Behavioral',
      rawInput:
        'Situation, Task, Action, Result stories with concrete examples and tighter executive summaries.',
      type: NoteType.BEHAVIORAL,
      status: NoteStatus.DRAFT,
      overrideRole: null,
      overrideLevel: null,
      overrideStack: [],
      overrideGoals: ['Behavioral storytelling'],
      overrideEnglishLevel: null,
      preferredOutputStyle: null,
      structuredContent: null,
      createdAt: new Date('2026-05-26T10:00:00.000Z'),
      updatedAt: new Date('2026-05-27T10:00:00.000Z'),
      questionCount: 3,
      difficulty: QuestionDifficulty.EASY,
    },
  ],
}
