import { LearningPathItemStatus } from '@interviewos/types'
import { CheckCheckIcon, CompassIcon, SparklesIcon } from 'lucide-react'

import { SectionCard, StatCard } from '../../../../components/ui/page'
import { Progress } from '../../../../components/ui/progress'
import type { LearningPathPageProps, ReadyLearningPathState } from '../LearningPathPage.types'
import {
  getLearningPathFocusItem,
  getLearningPathProgress,
  getLearningPathTypeSummaries,
  getLearningPathStatusGroups,
} from '../LearningPathPage.utils'
import { CoverageCard } from './CoverageCard'
import { FocusCard } from './FocusCard'
import { StatusSection } from './StatusSection'

type ReadyBodyProps = {
  state: ReadyLearningPathState
  renderItemActions?: LearningPathPageProps['renderItemActions']
}

export function ReadyBody({ state, renderItemActions }: ReadyBodyProps) {
  const progress = getLearningPathProgress(state.items)
  const completedCount = state.items.filter(
    (item) => item.status === LearningPathItemStatus.COMPLETED,
  ).length
  const groups = getLearningPathStatusGroups(state.items)
  const typeSummaries = getLearningPathTypeSummaries(state.items)
  const focusItem = getLearningPathFocusItem(state.items)

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {focusItem ? (
          <FocusCard focusItem={focusItem} renderItemActions={renderItemActions} />
        ) : null}
        <StatCard
          label="Path items"
          value={state.items.length}
          icon={CompassIcon}
          hint="Total tasks currently scheduled."
        />
        <StatCard
          label="Completed"
          value={completedCount}
          icon={CheckCheckIcon}
          hint="Finished and ready to archive."
        />
        <StatCard
          label="Track progress"
          value={`${progress}%`}
          icon={SparklesIcon}
          hint={`${state.items.length - completedCount} items still need attention.`}
        />
        <StatCard
          label="Item types"
          value={typeSummaries.length}
          hint="Grouped from current backend item.type values."
        />
      </div>

      <SectionCard
        title="Daily plan progress"
        description="A single queue for today's notes, drills, and follow-up practice generated by recent performance."
      >
        <div className="space-y-3">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm font-medium">
              {completedCount} of {state.items.length} completed
            </p>
            <p className="text-sm text-muted-foreground">{progress}% complete</p>
          </div>
          <Progress value={progress} className="h-3" />
        </div>
      </SectionCard>

      <SectionCard
        title="Coverage by type"
        description="Shows which categories are driving most of your current work."
      >
        <div className="grid gap-4 xl:grid-cols-3">
          {typeSummaries.map((summary) => (
            <CoverageCard key={summary.type} summary={summary} />
          ))}
        </div>
      </SectionCard>

      <div className="space-y-4">
        {groups.map((group) => (
          <StatusSection
            key={group.key}
            group={group}
            renderItemActions={renderItemActions}
          />
        ))}
      </div>
    </div>
  )
}
