export enum ExperienceLevel {
  JUNIOR = 'JUNIOR',
  MID = 'MID',
  SENIOR = 'SENIOR',
  STAFF = 'STAFF',
  PRINCIPAL = 'PRINCIPAL',
}

export enum EnglishLevel {
  BEGINNER = 'BEGINNER',
  ELEMENTARY = 'ELEMENTARY',
  INTERMEDIATE = 'INTERMEDIATE',
  UPPER_INTERMEDIATE = 'UPPER_INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  NATIVE = 'NATIVE',
}

export enum NoteStatus {
  DRAFT = 'DRAFT',
  REVIEWING = 'REVIEWING',
  NEEDS_PRACTICE = 'NEEDS_PRACTICE',
  INTERVIEW_READY = 'INTERVIEW_READY',
  MASTERED = 'MASTERED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum NoteType {
  CONCEPT = 'CONCEPT',
  ALGORITHM = 'ALGORITHM',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  BEHAVIORAL = 'BEHAVIORAL',
  LANGUAGE_SPECIFIC = 'LANGUAGE_SPECIFIC',
}

export enum InterviewType {
  TECHNICAL = 'TECHNICAL',
  BEHAVIORAL = 'BEHAVIORAL',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  MIXED = 'MIXED',
}

export enum QuestionDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  EXPERT = 'EXPERT',
}

export enum RecommendationStatus {
  PENDING = 'PENDING',
  DISMISSED = 'DISMISSED',
  COMPLETED = 'COMPLETED',
}

export enum EnglishNoteStatus {
  NEEDS_PRACTICE = 'NEEDS_PRACTICE',
  REVIEWING = 'REVIEWING',
  IMPROVED = 'IMPROVED',
  MASTERED = 'MASTERED',
}

export enum WeakConceptStatus {
  ACTIVE = 'ACTIVE',
  IMPROVING = 'IMPROVING',
  RESOLVED = 'RESOLVED',
  IGNORED = 'IGNORED',
}

export enum ReviewItemType {
  TECHNICAL_NOTE = 'TECHNICAL_NOTE',
  GENERATED_QUESTION = 'GENERATED_QUESTION',
  ENGLISH_NOTE = 'ENGLISH_NOTE',
  WEAK_CONCEPT = 'WEAK_CONCEPT',
}

export enum ReviewRating {
  AGAIN = 'AGAIN',
  HARD = 'HARD',
  GOOD = 'GOOD',
  EASY = 'EASY',
}

export enum LearningPathItemStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SNOOZED = 'SNOOZED',
  SKIPPED = 'SKIPPED',
}

export enum TurnRole {
  INTERVIEWER = 'INTERVIEWER',
  CANDIDATE = 'CANDIDATE',
}

export enum TurnDecision {
  FOLLOW_UP = 'FOLLOW_UP',
  DEEP_DIVE = 'DEEP_DIVE',
  CLARIFY = 'CLARIFY',
  CHALLENGE = 'CHALLENGE',
  ESCALATE = 'ESCALATE',
  ADVANCE = 'ADVANCE',
  WRAP_UP = 'WRAP_UP',
  EVALUATE = 'EVALUATE',
}

export enum SessionMode {
  STANDARD = 'STANDARD',
  MULTI_TURN = 'MULTI_TURN',
  COMPANY = 'COMPANY',
}

export enum EvaluationStatus {
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
}

export enum StarDimension {
  SITUATION = 'SITUATION',
  TASK = 'TASK',
  ACTION = 'ACTION',
  RESULT = 'RESULT',
}

export enum ExplanationDepth {
  QUICK = 'QUICK',
  STANDARD = 'STANDARD',
  DEEP = 'DEEP',
  INTERVIEW = 'INTERVIEW',
}
