import { LearningPathItemStatus } from '@interviewos/types'
import { CheckCheckIcon, CompassIcon, SparklesIcon } from 'lucide-react'

import { Button } from '../../../components/ui/button'
import { EmptyState, PageHeader, SectionCard, StatCard } from '../../../components/ui/page'
import { Progress } from '../../../components/ui/progress'
import { Skeleton } from '../../../components/ui/skeleton'
import ConsoleLayout from '../../layouts/ConsoleLayout'
import { LearningPathListItem } from '../../molecules/LearningPathListItem/LearningPathListItem'
import { learningPathFixture } from './LearningPathPage.fixtures'
import type { LearningPathPageProps } from './LearningPathPage.types'
import {
  formatLearningPathLabel,
  getLearningPathFocusItem,
  getLearningPathProgress,
  getLearningPathStatusClassName,
  getLearningPathStatusGroups,
  getLearningPathTypeSummaries,
} from './LearningPathPage.utils'

function LearningPathBody({ items }: { items: NonNullable<LearningPathPageProps['items']> }) {
  const progress = getLearningPathProgress(items)
  const completedCount = items.filter((item) => item.status === LearningPathItemStatus.COMPLETED).length
  const groups = getLearningPathStatusGroups(items)
  const typeSummaries = getLearningPathTypeSummaries(items)
  const focusItem = getLearningPathFocusItem(items)

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-[minmax(0,1.35fr)_repeat(3,minmax(0,1fr))]">
        {focusItem ? (
          <div className="rounded-3xl border border-primary/15 bg-[linear-gradient(135deg,color-mix(in_oklch,var(--primary),white_92%)_0%,white_100%)] p-5 shadow-[0_20px_60px_-38px_color-mix(in_oklch,var(--primary),transparent_42%)]">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary/80">
              Focus next
            </p>
            <p className="mt-3 font-heading text-2xl font-semibold tracking-tight">
              {focusItem.title}
            </p>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">{focusItem.reason}</p>
            <div className="mt-4 flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
              <span className="rounded-full border border-primary/10 bg-white/80 px-3 py-1 font-medium text-foreground">
                Priority {focusItem.priorityScore}
              </span>
              <span>{formatLearningPathLabel(focusItem.type)}</span>
            </div>
          </div>
        ) : null}
        <StatCard
          label="Path items"
          value={items.length}
          icon={CompassIcon}
          hint="Total tasks currently scheduled."
        />
        <StatCard
          label="Completed"
          value={completedCount}
          icon={CheckCheckIcon}
          hint="Finished and ready to archive."
        />
        <StatCard
          label="Track progress"
          value={`${progress}%`}
          icon={SparklesIcon}
          hint={`${items.length - completedCount} items still need attention.`}
        />
        <StatCard
          label="Item types"
          value={typeSummaries.length}
          hint="Grouped from current backend item.type values."
        />
      </div>

      <SectionCard
        title="Overall progress"
        description="A single queue for notes, drills, and follow-up practice generated by recent performance."
      >
        <div className="space-y-3">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm font-medium">
              {completedCount} of {items.length} completed
            </p>
            <p className="text-sm text-muted-foreground">{progress}% complete</p>
          </div>
          <Progress value={progress} className="h-3" />
        </div>
      </SectionCard>

      <SectionCard
        title="Coverage by type"
        description="Shows which categories are driving most of your current work."
      >
        <div className="grid gap-4 xl:grid-cols-3">
          {typeSummaries.map((summary) => {
            const typeProgress =
              summary.total === 0 ? 0 : Math.round((summary.completed / summary.total) * 100)

            return (
              <div
                key={summary.type}
                className="rounded-2xl border border-border/80 bg-[linear-gradient(180deg,white_0%,color-mix(in_oklch,var(--muted),white_55%)_100%)] p-4"
              >
                <p className="text-sm font-semibold">{formatLearningPathLabel(summary.type)}</p>
                <p className="mt-2 text-2xl font-semibold tracking-tight">
                  {summary.completed}/{summary.total}
                </p>
                <Progress value={typeProgress} className="mt-3 h-2" />
                <p className="mt-2 text-xs text-muted-foreground">{typeProgress}% completed</p>
              </div>
            )
          })}
        </div>
      </SectionCard>

      <div className="space-y-4">
        {groups.map((group) => (
          <SectionCard
            key={group.key}
            title={group.label}
            description={`${group.items.length} items in this stage`}
          >
            <div className="space-y-3">
              {group.items.map((item) => (
                <LearningPathListItem
                  key={item.id}
                  badges={[
                    {
                      label: formatLearningPathLabel(item.type),
                      variant: 'secondary',
                      className: 'rounded-full px-3 py-1',
                    },
                    {
                      label: formatLearningPathLabel(item.status),
                      variant: 'outline',
                      className: getLearningPathStatusClassName(item.status),
                    },
                  ]}
                  title={item.title}
                  description={item.reason}
                  priorityValue={item.priorityScore}
                  footer={item.actionPath}
                  action={
                    <Button variant="outline" size="sm">
                      Open task
                    </Button>
                  }
                />
              ))}
            </div>
          </SectionCard>
        ))}
      </div>
    </div>
  )
}

function LoadingBody() {
  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {Array.from({ length: 4 }).map((_, index) => (
          <Skeleton key={index} className="h-28 rounded-2xl" />
        ))}
      </div>
      <Skeleton className="h-36 rounded-2xl" />
      <div className="space-y-3">
        {Array.from({ length: 3 }).map((_, index) => (
          <Skeleton key={index} className="h-40 rounded-2xl" />
        ))}
      </div>
    </div>
  )
}

function ErrorBody({ message }: { message: string }) {
  return (
    <EmptyState
      className="min-h-128 border-destructive/20 bg-destructive/5"
      title={<span className="text-destructive">Failed to load learning path</span>}
      description={message}
      action={<Button variant="destructive">Retry</Button>}
    />
  )
}

function EmptyBody() {
  return (
    <EmptyState
      className="min-h-96"
      icon={CompassIcon}
      title="No learning path items yet"
      description="Review activity, interview feedback, and weak concepts will generate your next steps here."
      action={<Button>Go to review queue</Button>}
    />
  )
}

function Root({ items = learningPathFixture.items, loading, empty, error }: LearningPathPageProps) {
  return (
    <ConsoleLayout title="Learning path">
      <PageHeader
        title="Learning path"
        description="A prioritized queue of what to study next, based on recent weakness signals and review outcomes."
        actions={
          <Button variant="outline" size="lg">
            Focus mode
          </Button>
        }
      />
      {error ? (
        <ErrorBody message={error} />
      ) : loading ? (
        <LoadingBody />
      ) : empty || items.length === 0 ? (
        <EmptyBody />
      ) : (
        <LearningPathBody items={items} />
      )}
    </ConsoleLayout>
  )
}

const LearningPathPage = Object.assign(Root, {
  LearningPathListItem,
})

export default LearningPathPage
