import { LearningPathItem, LearningPathItemStatus } from '@interviewos/types'
import { CheckCheckIcon, CompassIcon, SparklesIcon } from 'lucide-react'

import { Button } from '../../../components/ui/button'
import {
  EmptyState,
  PageBody,
  PageHeader,
  SectionCard,
  StatCard,
} from '../../../components/ui/page'
import { Progress } from '../../../components/ui/progress'
import { Skeleton } from '../../../components/ui/skeleton'
import { LearningPathListItem } from '../../molecules/LearningPathListItem/LearningPathListItem'
import type { LearningPathPageProps } from './LearningPathPage.types'
import {
  formatLearningPathLabel,
  getLearningPathEstimatedTimeLabel,
  getLearningPathFocusItem,
  getLearningPathProgress,
  getLearningPathStatusClassName,
  getLearningPathStatusGroups,
  getLearningPathTypeSummaries,
} from './LearningPathPage.utils'

function LearningPathBody({
  items,
  renderItemActions,
}: {
  items: LearningPathItem[]
  renderItemActions?: LearningPathPageProps['renderItemActions']
}) {
  const progress = getLearningPathProgress(items)
  const completedCount = items.filter(
    (item) => item.status === LearningPathItemStatus.COMPLETED,
  ).length
  const groups = getLearningPathStatusGroups(items)
  const typeSummaries = getLearningPathTypeSummaries(items)
  const focusItem = getLearningPathFocusItem(items)

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {focusItem ? (
          <div className="rounded-xl border border-primary/20 bg-accent-soft p-5 md:col-span-2 xl:col-span-4">
            <p className="text-xs font-semibold uppercase text-primary/80">Today&apos;s focus</p>
            <p className="mt-3 font-heading text-2xl font-semibold tracking-tight">
              {focusItem.title}
            </p>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">{focusItem.reason}</p>
            <div className="mt-4 flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
              <span className="rounded-md border border-primary/20 bg-background px-3 py-1 font-medium text-foreground">
                Priority {focusItem.priorityScore}
              </span>
              <span>{formatLearningPathLabel(focusItem.type)}</span>
              <span>Estimated time: {getLearningPathEstimatedTimeLabel(focusItem)}</span>
            </div>
            {renderItemActions ? <div className="mt-5">{renderItemActions(focusItem)}</div> : null}
          </div>
        ) : null}
        <StatCard
          label="Path items"
          value={items.length}
          icon={CompassIcon}
          hint="Total tasks currently scheduled."
        />
        <StatCard
          label="Completed"
          value={completedCount}
          icon={CheckCheckIcon}
          hint="Finished and ready to archive."
        />
        <StatCard
          label="Track progress"
          value={`${progress}%`}
          icon={SparklesIcon}
          hint={`${items.length - completedCount} items still need attention.`}
        />
        <StatCard
          label="Item types"
          value={typeSummaries.length}
          hint="Grouped from current backend item.type values."
        />
      </div>

      <SectionCard
        title="Daily plan progress"
        description="A single queue for today's notes, drills, and follow-up practice generated by recent performance."
      >
        <div className="space-y-3">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm font-medium">
              {completedCount} of {items.length} completed
            </p>
            <p className="text-sm text-muted-foreground">{progress}% complete</p>
          </div>
          <Progress value={progress} className="h-3" />
        </div>
      </SectionCard>

      <SectionCard
        title="Coverage by type"
        description="Shows which categories are driving most of your current work."
      >
        <div className="grid gap-4 xl:grid-cols-3">
          {typeSummaries.map((summary) => {
            const typeProgress =
              summary.total === 0 ? 0 : Math.round((summary.completed / summary.total) * 100)

            return (
              <div key={summary.type} className="rounded-md border border-border/80 bg-muted p-4">
                <p className="text-sm font-semibold">{formatLearningPathLabel(summary.type)}</p>
                <p className="mt-2 text-2xl font-semibold tracking-tight">
                  {summary.completed}/{summary.total}
                </p>
                <Progress value={typeProgress} className="mt-3 h-2" />
                <p className="mt-2 text-xs text-muted-foreground">{typeProgress}% completed</p>
              </div>
            )
          })}
        </div>
      </SectionCard>

      <div className="space-y-4">
        {groups.map((group) => (
          <SectionCard
            key={group.key}
            title={group.label}
            description={`${group.items.length} items in this stage`}
          >
            <div className="space-y-3">
              {group.items.map((item) => (
                <LearningPathListItem
                  key={item.id}
                  badges={[
                    {
                      label: formatLearningPathLabel(item.type),
                      variant: 'secondary',
                      className: 'rounded-full px-3 py-1',
                    },
                    {
                      label: formatLearningPathLabel(item.status),
                      variant: 'outline',
                      className: getLearningPathStatusClassName(item.status),
                    },
                  ]}
                  title={item.title}
                  description={item.reason}
                  priorityValue={item.priorityScore}
                  footer={`Estimated time: ${getLearningPathEstimatedTimeLabel(item)}`}
                  action={
                    renderItemActions ? (
                      renderItemActions(item)
                    ) : (
                      <Button variant="outline" size="sm">
                        Open task
                      </Button>
                    )
                  }
                />
              ))}
            </div>
          </SectionCard>
        ))}
      </div>
    </div>
  )
}

function LoadingBody() {
  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {Array.from({ length: 4 }).map((_, index) => (
          <Skeleton key={index} className="h-28 rounded-md" />
        ))}
      </div>
      <Skeleton className="h-36 rounded-md" />
      <div className="space-y-3">
        {Array.from({ length: 3 }).map((_, index) => (
          <Skeleton key={index} className="h-40 rounded-md" />
        ))}
      </div>
    </div>
  )
}

function ErrorBody({ message, retryHref }: { message: string; retryHref?: string }) {
  return (
    <EmptyState
      className="min-h-128 border-destructive/20 bg-destructive/5"
      title={<span className="text-destructive">Failed to load learning path</span>}
      description={message}
      action={
        retryHref ? (
          <Button asChild variant="destructive">
            <a href={retryHref}>Retry</a>
          </Button>
        ) : undefined
      }
    />
  )
}

function EmptyBody({ reviewQueueHref }: { reviewQueueHref: string }) {
  return (
    <EmptyState
      className="min-h-96"
      icon={CompassIcon}
      title="No learning path items yet"
      description="Review activity, interview feedback, and weak concepts will generate your next steps here."
      action={
        <Button asChild>
          <a href={reviewQueueHref}>Go to review queue</a>
        </Button>
      }
    />
  )
}

function Root({
  state,
  reviewQueueHref,
  focusModeHref,
  retryHref,
  renderItemActions,
}: LearningPathPageProps) {
  return (
    <>
      <PageHeader
        title="Learning path"
        description="A prioritized queue of what to study next, based on recent weakness signals and review outcomes."
        actions={
          focusModeHref ? (
            <Button asChild variant="outline" size="lg">
              <a href={focusModeHref}>Focus mode</a>
            </Button>
          ) : undefined
        }
      />

      <PageBody>
        {state.kind === 'error' ? (
          <ErrorBody message={state.message} retryHref={retryHref} />
        ) : state.kind === 'loading' ? (
          <LoadingBody />
        ) : state.kind === 'empty' ? (
          <EmptyBody reviewQueueHref={reviewQueueHref} />
        ) : (
          <LearningPathBody items={state.items} renderItemActions={renderItemActions} />
        )}
      </PageBody>
    </>
  )
}

const LearningPathPage = Object.assign(Root, {
  LearningPathListItem,
})

export default LearningPathPage
