import type { ReadinessPageFixture } from './ReadinessPage.types'

export const readinessPageFixture: ReadinessPageFixture = {
  title: 'Interview readiness',
  subtitle: 'A composite score across technical, behavioral, English, and consistency.',
  recomputeLabel: 'Recompute',
  latest: {
    id: 'readiness-snapshot-6',
    userId: 'user-1',
    overallScore: 76,
    confidenceLevel: 0.88,
    technicalMastery: 68,
    interviewPerformance: 74,
    behavioralPerformance: 82,
    systemDesignPerformance: 61,
    englishCommunication: 81,
    reviewCompletion: 88,
    learningProgress: 72,
    breakdown: [
      {
        dimension: 'technicalMastery',
        label: 'Technical mastery',
        score: 68,
        weight: 0.2,
        trend: 'UP',
      },
      {
        dimension: 'interviewPerformance',
        label: 'Interview performance',
        score: 74,
        weight: 0.2,
        trend: 'UP',
      },
      {
        dimension: 'behavioralPerformance',
        label: 'Behavioral performance',
        score: 82,
        weight: 0.15,
        trend: 'UP',
      },
      {
        dimension: 'systemDesignPerformance',
        label: 'System design performance',
        score: 61,
        weight: 0.15,
        trend: 'STABLE',
      },
      {
        dimension: 'englishCommunication',
        label: 'English communication',
        score: 81,
        weight: 0.15,
        trend: 'UP',
      },
      {
        dimension: 'reviewCompletion',
        label: 'Review completion',
        score: 88,
        weight: 0.15,
        trend: 'UP',
      },
    ],
    improvementTrend: 4,
    computedAt: new Date('2026-06-05T09:42:00+07:00'),
  },
  history: [
    {
      id: 'readiness-history-1',
      overallScore: 76,
      improvementTrend: 4,
      computedAt: new Date('2026-06-04T09:42:00+07:00'),
    },
    {
      id: 'readiness-history-2',
      overallScore: 72,
      improvementTrend: 2,
      computedAt: new Date('2026-06-02T09:42:00+07:00'),
    },
    {
      id: 'readiness-history-3',
      overallScore: 70,
      improvementTrend: 0,
      computedAt: new Date('2026-05-30T09:42:00+07:00'),
    },
    {
      id: 'readiness-history-4',
      overallScore: 70,
      improvementTrend: -3,
      computedAt: new Date('2026-05-27T09:42:00+07:00'),
    },
    {
      id: 'readiness-history-5',
      overallScore: 73,
      improvementTrend: 5,
      computedAt: new Date('2026-05-24T09:42:00+07:00'),
    },
    {
      id: 'readiness-history-6',
      overallScore: 68,
      improvementTrend: 1,
      computedAt: new Date('2026-05-20T09:42:00+07:00'),
    },
  ],
}
